# Generated by Django 5.1.6 on 2025-02-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Categories')),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=75)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('author', models.CharField(max_length=50)),
                ('summarry', models.TextField(max_length=200000)),
                ('pdf', models.FileField(upload_to='pdf')),
                ('recommended_books', models.BooleanField(default=False)),
                ('Fiction_books', models.BooleanField(default=False)),
                ('bussiness_books', models.BooleanField(default=False)),
                ('Health_books', models.BooleanField(default=False)),
                ('literature_books', models.BooleanField(default=False)),
                ('Religious_books', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='books', to='book.category')),
            ],
        ),
    ]
